### Market basket analysis project

The market basket analysis project utilizes the mlxtend library to analyze purchase patterns and associations in a retail dataset. The dataset, named "online_retail_II.xlsx", is read using the pd.ExcelFile function and stored in a dataframe called "retail".

The dataframe contains the following columns:
- Invoice: The unique identifier for each transaction.
- StockCode: The code for the item purchased.
- Description: The description of the item.
- Quantity: The quantity of the item purchased.
- InvoiceDate: The date and time of the transaction.
- Price: The price of the item.
- Customer ID: The unique identifier for each customer.
- Country: The country where the transaction took place.

The project aims to uncover associations between items frequently purchased together. It uses the Apriori algorithm from the mlxtend library to identify frequent itemsets, which are sets of items that appear together in a specified minimum number of transactions. The parameter "min_support" is set to determine the minimum support threshold for an itemset to be considered frequent.

Once the frequent itemsets are obtained, association rules are generated using the association_rules function. These rules indicate the likelihood of one item being purchased given the presence of another item(s) in a transaction. The parameters "min_threshold" and "metric" are used to set the minimum confidence threshold and the evaluation metric to be used in the rule generation process.

By analyzing the generated association rules, retailers can gain insights into product bundling, cross-selling opportunities, and customer purchasing behavior. This project can be a valuable tool for optimizing marketing strategies, improving product recommendations, and enhancing overall sales performance.

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Create an ExcelFile object using the pd.ExcelFile function
xlsx = pd.ExcelFile('online_retail_II.xlsx')

# Read the data from the Excel file into a dataframe called "retail"
retail = pd.read_excel(xlsx)

# Display the first few rows of the dataframe using the .head() function
retail.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [3]:
retail.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [4]:
# Remove leading and trailing whitespaces from the 'Description' column
retail['Description'] = retail['Description'].str.strip()

# Drop rows with missing values in the 'Description' column
retail.dropna(axis=0, subset=['Description'], inplace=True)

# Convert the 'Invoice' column to string type and rename it as 'InvoiceNo'
retail['InvoiceNo'] = retail['Invoice'].astype('str')

In [5]:
# Filter the data for transactions from France, group by 'Invoice' and 'Description', and sum up the 'Quantity' for each group
basket = (retail[retail['Country'] == "France"]
          .groupby(['Invoice', 'Description'])['Quantity']
          .sum()
          
          # Unstack the data to create a pivot table with 'Description' as column headers
          .unstack()
          
          # Reset the index to have 'Invoice' as a regular column
          .reset_index()
          
          # Fill any missing values with 0
          .fillna(0)
          
          # Set the 'Invoice' column as the index
          .set_index('Invoice')
         )

In [6]:
basket.head()

Description,10 COLOUR SPACEBOY PEN,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE POSY,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE RED SPOTTY,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,...,WRAP PINK FAIRY CAKES,WRAP RED APPLES,WRAP SUKI AND FRIENDS,WRAP WINTER FOREST,"WRAP, CAROUSEL",YELLOW BREAKFAST CUP AND SAUCER,YELLOW RED FLOWER PIGGY BANK,YOU'RE CONFUSING ME METAL SIGN,ZINC METAL HEART DECORATION,ZINC WILLIE WINKIE CANDLE STICK
Invoice,,,,,,,,,,,,,,,,,,,,,
489439,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0
489883,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
490139,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
490152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
def encode_units(x):
    # If the quantity is less than or equal to 0, return 0
    if x <= 0:
        return 0
    # If the quantity is greater than or equal to 1, return 1
    if x >= 1:
        return 1

# Apply the 'encode_units' function to the 'basket' dataframe
basket_sets = basket.applymap(encode_units)

# Drop the 'POSTAGE' column from the 'basket_sets' dataframe
basket_sets.drop('POSTAGE', inplace=True, axis=1)

In [8]:
# Generate frequent itemsets using apriori
frequent_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)

## Final Recommended Products

In [9]:
# Generate association rules using frequent_itemsets with metric='lift' and min_threshold=1
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)

# Display the first few rows of the rules dataframe
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(CIRCUS PARADE LUNCH BOX),(SPACEBOY LUNCH BOX),0.094276,0.107744,0.070707,0.750000,6.960938,0.060549,3.569024,0.945477
1,(SPACEBOY LUNCH BOX),(CIRCUS PARADE LUNCH BOX),0.107744,0.094276,0.070707,0.656250,6.960938,0.060549,2.634833,0.959748
2,(STRAWBERRY LUNCH BOX WITH CUTLERY),(LUNCH BOX WITH CUTLERY RETROSPOT),0.121212,0.141414,0.097643,0.805556,5.696429,0.080502,4.415584,0.938169
3,(LUNCH BOX WITH CUTLERY RETROSPOT),(STRAWBERRY LUNCH BOX WITH CUTLERY),0.141414,0.121212,0.097643,0.690476,5.696429,0.080502,2.839161,0.960243
4,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN CIRCUS PARADE),0.094276,0.131313,0.074074,0.785714,5.983516,0.061694,4.053872,0.919567

In [10]:
rules.shape

(14, 10)